version: '3.7'
services:
  app-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kontschedule?useSSL=false
      SPRING_DATASOURCE_USERNAME: kontulari
      SPRING_DATASOURCE_PASSWORD: kontulari
    networks:
      - backend
      - frontend
  app-client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: kontschedule
      MYSQL_USER: kontulari
      MYSQL_PASSWORD: kontulari
      MYSQL_ROOT_PASSWORD: kontulari
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
volumes:
  db:
networks:
  backend:
  frontend:
